env:
  browser: true
  es2020: true
extends:
  - 'plugin:react/recommended'
  - 'plugin:react-hooks/recommended'
  - 'prettier'
parser: '@babel/eslint-parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
plugins:
  - react
  - prettier
  - jsx
rules:
  prettier/prettier: 'error'
  prefer-const: 0
