services:
  dev:
    build: .
    ports:
      - 3000:3000

  ipfs:
    container_name: ipfs
    image: ipfs/go-ipfs:release
    ports:
      - '4001:4001'
      - '5001:5001'
      - '8080:8080'
    volumes:
      - ipfs:/data/ipfs
      - ./cors.sh:/cors.sh
      - ./start_ipfs.sh:/start_ipfs.sh
    entrypoint: /bin/sh /start_ipfs.sh
    #command: /start-ipfs.sh

volumes:
  fennel-app:
  ipfs:
